version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: trade_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trade
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre -d trade"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
